# Data Quality Review: Novozymes Enzyme Stability Dataset

In [1]:
import pandas as pd

## Step 1 : Import Data

In [2]:
train = pd.read_csv("data/train.csv")

In [3]:
train.shape

(31390, 5)

In [4]:
train.head()

,seq_id,protein_sequence,pH,data_source,tm
0,0,AAAAKAAALALLGEAPEVVDIWLPAGWRQPFRVFRLERKGDGVLVG...,7.0,doi.org/10.1038/s41592-020-0801-4,75.7
1,1,AAADGEPLHNEEERAGAGQVGRSLPQESEEQRTGSRPRRRRDLGSR...,7.0,doi.org/10.1038/s41592-020-0801-4,50.5
2,2,AAAFSTPRATSYRILSSAGSGSTRADAPQVRRLHTTRDLLAKDYYA...,7.0,doi.org/10.1038/s41592-020-0801-4,40.5
3,3,AAASGLRTAIPAQPLRHLLQPAPRPCLRPFGLLSVRAGSARRSGLL...,7.0,doi.org/10.1038/s41592-020-0801-4,47.2
4,4,AAATKSGPRRQSQGASVRTFTPFYFLVEPVDTLSVRGSSVILNCSA...,7.0,doi.org/10.1038/s41592-020-0801-4,49.5

In [5]:
train.dtypes

seq_id                int64
protein_sequence        str
pH                  float64
data_source             str
tm                  float64
dtype: object

## Step 2 : Missing values

In [8]:
train.isna().sum()

seq_id                 0
protein_sequence       0
pH                   286
data_source         3347
tm                     0
dtype: int64

In [10]:
(train.isna().mean()* 100).round(2)

seq_id               0.00
protein_sequence     0.00
pH                   0.91
data_source         10.66
tm                   0.00
dtype: float64

the raw counts of NA values are as follows 286 in pH, and 3,347 in data_source. That is 0.91% of the pH column and 10.7% of the data_soure column. I noticed that there was an offical update I will look at that file first then make my decision in reagrds to data exculsion.

## Step 3: Apply the offical updates

In [13]:
updates = pd.read_csv("data/train_updates_20220929.csv")

In [15]:
updates.head()

   seq_id protein_sequence  pH  data_source  tm
0      69              NaN NaN          NaN NaN
1      70              NaN NaN          NaN NaN
2      71              NaN NaN          NaN NaN
3      72              NaN NaN          NaN NaN
4      73              NaN NaN          NaN NaN

In [17]:
updates.dtypes

seq_id                int64
protein_sequence        str
pH                  float64
data_source         float64
tm                  float64
dtype: object

In [18]:
updates.shape

(2434, 5)

In [20]:
updates.isna().sum()

seq_id                 0
protein_sequence    2409
pH                  2409
data_source         2434
tm                  2409
dtype: int64

In [21]:
updates[updates["pH"].notna()]

,seq_id,protein_sequence,pH,data_source,tm
25,973,DTSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
28,986,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVTFQNRESVLPT...,7.0,NaN,48.4
29,988,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,7.0,NaN,49.0
30,989,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,5.5,NaN,55.6
33,1003,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESTLPT...,7.0,NaN,48.4
38,1012,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
39,1014,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
40,1018,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
46,1037,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
47,1042,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
57,1079,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
58,1081,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
59,1088,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
60,1093,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
61,1096,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
62,1098,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
63,1100,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
64,1108,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,7.0,NaN,49.0
65,1111,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,5.5,NaN,55.6
66,1120,DVSGTVCLSALPPEATDVLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
68,1122,DVSGTVCLSALPPEAVDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
69,1125,DVSGVVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
965,13447,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
966,13449,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
1079,14640,MKMSRLCLSVALLVLLGTLAASTPGCDTSNQAKAQRPDFCLEPPYT...,7.0,NaN,39.0

In [22]:
fix_ids = updates[updates["pH"].notna()]["seq_id"]

In [23]:
train[train["seq_id"].isin(fix_ids)]

,seq_id,protein_sequence,pH,data_source,tm
973,973,DTSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
986,986,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVTFQNRESVLPT...,48.4,NaN,7.0
988,988,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,49.0,NaN,7.0
989,989,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,55.6,NaN,5.5
1003,1003,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESTLPT...,48.4,NaN,7.0
1012,1012,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1014,1014,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,55.6,NaN,5.5
1018,1018,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,49.0,NaN,7.0
1037,1037,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,49.0,NaN,7.0
1042,1042,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1079,1079,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,55.6,NaN,5.5
1081,1081,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,49.0,NaN,7.0
1088,1088,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1093,1093,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1096,1096,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1098,1098,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1100,1100,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,55.6,NaN,5.5
1108,1108,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,49.0,NaN,7.0
1111,1111,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,55.6,NaN,5.5
1120,1120,DVSGTVCLSALPPEATDVLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1122,1122,DVSGTVCLSALPPEAVDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1125,1125,DVSGVVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
13447,13447,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,64.9,NaN,0.2
13449,13449,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,64.9,NaN,0.1
14640,14640,MKMSRLCLSVALLVLLGTLAASTPGCDTSNQAKAQRPDFCLEPPYT...,39.0,NaN,0.0

In [24]:
train_clean = train.copy()

In [25]:
# identifying the na rows. 
delete_ids = updates[updates["pH"].isna()]["seq_id"]

In [27]:
train_clean = train_clean[~train_clean["seq_id"].isin(delete_ids)]

In [28]:
train_clean.shape

(28981, 5)

In [29]:
31390-2409

28981

In [30]:
fixes = updates[updates["pH"].notna()].set_index("seq_id")

In [31]:
train_clean = train_clean.set_index("seq_id")

In [32]:
#overwriting the values with the correct ones 
train_clean.loc[fixes.index,["pH","tm"]] = fixes[["pH","tm"]]

In [33]:
train_clean = train_clean.reset_index()

In [34]:
train_clean[train_clean["seq_id"].isin(fix_ids)]

,seq_id,protein_sequence,pH,data_source,tm
948,973,DTSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
959,986,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVTFQNRESVLPT...,7.0,NaN,48.4
961,988,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,7.0,NaN,49.0
962,989,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,5.5,NaN,55.6
974,1003,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESTLPT...,7.0,NaN,48.4
979,1012,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
981,1014,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
985,1018,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
999,1037,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
1004,1042,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1032,1079,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
1034,1081,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
1041,1088,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1046,1093,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1049,1096,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1051,1098,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1053,1100,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
1061,1108,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,7.0,NaN,49.0
1064,1111,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,5.5,NaN,55.6
1073,1120,DVSGTVCLSALPPEATDVLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1074,1122,DVSGTVCLSALPPEAVDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1077,1125,DVSGVVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
12504,13447,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
12506,13449,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
13585,14640,MKMSRLCLSVALLVLLGTLAASTPGCDTSNQAKAQRPDFCLEPPYT...,7.0,NaN,39.0

After examining the update file, I found 2,409 rows with missing values in every column except seq_id. Following Kaggle's instructions, I deleted these rows from the training data. The other 25 rows correct entries where pH and tm were swapped in the original data, so I overwrote those rows with the corrected values from the update file. The cleaned dataset has 28,981 rows.