# Data Quality Review: Novozymes Enzyme Stability Dataset

In [1]:
import pandas as pd

## Step 1 : Import Data

In [2]:
train = pd.read_csv("data/train.csv")

In [3]:
train.shape

(31390, 5)

In [4]:
train.head()

,seq_id,protein_sequence,pH,data_source,tm
0,0,AAAAKAAALALLGEAPEVVDIWLPAGWRQPFRVFRLERKGDGVLVG...,7.0,doi.org/10.1038/s41592-020-0801-4,75.7
1,1,AAADGEPLHNEEERAGAGQVGRSLPQESEEQRTGSRPRRRRDLGSR...,7.0,doi.org/10.1038/s41592-020-0801-4,50.5
2,2,AAAFSTPRATSYRILSSAGSGSTRADAPQVRRLHTTRDLLAKDYYA...,7.0,doi.org/10.1038/s41592-020-0801-4,40.5
3,3,AAASGLRTAIPAQPLRHLLQPAPRPCLRPFGLLSVRAGSARRSGLL...,7.0,doi.org/10.1038/s41592-020-0801-4,47.2
4,4,AAATKSGPRRQSQGASVRTFTPFYFLVEPVDTLSVRGSSVILNCSA...,7.0,doi.org/10.1038/s41592-020-0801-4,49.5

In [5]:
train.dtypes

seq_id                int64
protein_sequence        str
pH                  float64
data_source             str
tm                  float64
dtype: object

## Step 2 : Missing values

In [6]:
train.isna().sum()

seq_id                 0
protein_sequence       0
pH                   286
data_source         3347
tm                     0
dtype: int64

In [7]:
(train.isna().mean()* 100).round(2)

seq_id               0.00
protein_sequence     0.00
pH                   0.91
data_source         10.66
tm                   0.00
dtype: float64

the raw counts of NA values are as follows 286 in pH, and 3,347 in data_source. That is 0.91% of the pH column and 10.7% of the data_soure column. I noticed that there was an offical update I will look at that file first then make my decision in reagrds to data exculsion.

## Step 3: Apply the offical updates

In [8]:
updates = pd.read_csv("data/train_updates_20220929.csv")

In [9]:
updates.head()

   seq_id protein_sequence  pH  data_source  tm
0      69              NaN NaN          NaN NaN
1      70              NaN NaN          NaN NaN
2      71              NaN NaN          NaN NaN
3      72              NaN NaN          NaN NaN
4      73              NaN NaN          NaN NaN

In [10]:
updates.dtypes

seq_id                int64
protein_sequence        str
pH                  float64
data_source         float64
tm                  float64
dtype: object

In [11]:
updates.shape

(2434, 5)

In [12]:
updates.isna().sum()

seq_id                 0
protein_sequence    2409
pH                  2409
data_source         2434
tm                  2409
dtype: int64

In [13]:
updates[updates["pH"].notna()]

,seq_id,protein_sequence,pH,data_source,tm
25,973,DTSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
28,986,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVTFQNRESVLPT...,7.0,NaN,48.4
29,988,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,7.0,NaN,49.0
30,989,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,5.5,NaN,55.6
33,1003,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESTLPT...,7.0,NaN,48.4
38,1012,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
39,1014,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
40,1018,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
46,1037,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
47,1042,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
57,1079,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
58,1081,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
59,1088,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
60,1093,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
61,1096,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
62,1098,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
63,1100,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
64,1108,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,7.0,NaN,49.0
65,1111,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,5.5,NaN,55.6
66,1120,DVSGTVCLSALPPEATDVLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
68,1122,DVSGTVCLSALPPEAVDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
69,1125,DVSGVVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
965,13447,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
966,13449,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
1079,14640,MKMSRLCLSVALLVLLGTLAASTPGCDTSNQAKAQRPDFCLEPPYT...,7.0,NaN,39.0

In [14]:
fix_ids = updates[updates["pH"].notna()]["seq_id"]

In [15]:
train[train["seq_id"].isin(fix_ids)]

,seq_id,protein_sequence,pH,data_source,tm
973,973,DTSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
986,986,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVTFQNRESVLPT...,48.4,NaN,7.0
988,988,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,49.0,NaN,7.0
989,989,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,55.6,NaN,5.5
1003,1003,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESTLPT...,48.4,NaN,7.0
1012,1012,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1014,1014,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,55.6,NaN,5.5
1018,1018,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,49.0,NaN,7.0
1037,1037,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,49.0,NaN,7.0
1042,1042,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1079,1079,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,55.6,NaN,5.5
1081,1081,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,49.0,NaN,7.0
1088,1088,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1093,1093,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1096,1096,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1098,1098,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1100,1100,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,55.6,NaN,5.5
1108,1108,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,49.0,NaN,7.0
1111,1111,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,55.6,NaN,5.5
1120,1120,DVSGTVCLSALPPEATDVLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1122,1122,DVSGTVCLSALPPEAVDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
1125,1125,DVSGVVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,48.4,NaN,7.0
13447,13447,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,64.9,NaN,0.2
13449,13449,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,64.9,NaN,0.1
14640,14640,MKMSRLCLSVALLVLLGTLAASTPGCDTSNQAKAQRPDFCLEPPYT...,39.0,NaN,0.0

In [16]:
train_clean = train.copy()

In [17]:
# identifying the na rows. 
delete_ids = updates[updates["pH"].isna()]["seq_id"]

In [18]:
train_clean = train_clean[~train_clean["seq_id"].isin(delete_ids)]

In [19]:
train_clean.shape

(28981, 5)

In [20]:
31390-2409

28981

In [21]:
fixes = updates[updates["pH"].notna()].set_index("seq_id")

In [22]:
train_clean = train_clean.set_index("seq_id")

In [23]:
#overwriting the values with the correct ones 
train_clean.loc[fixes.index,["pH","tm"]] = fixes[["pH","tm"]]

In [24]:
train_clean = train_clean.reset_index()

In [25]:
train_clean[train_clean["seq_id"].isin(fix_ids)]

,seq_id,protein_sequence,pH,data_source,tm
948,973,DTSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
959,986,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVTFQNRESVLPT...,7.0,NaN,48.4
961,988,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,7.0,NaN,49.0
962,989,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFANRESVLPT...,5.5,NaN,55.6
974,1003,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESTLPT...,7.0,NaN,48.4
979,1012,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
981,1014,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
985,1018,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
999,1037,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
1004,1042,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1032,1079,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
1034,1081,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,49.0
1041,1088,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1046,1093,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1049,1096,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1051,1098,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1053,1100,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,5.5,NaN,55.6
1061,1108,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,7.0,NaN,49.0
1064,1111,DVSGTVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRKSVLPT...,5.5,NaN,55.6
1073,1120,DVSGTVCLSALPPEATDVLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1074,1122,DVSGTVCLSALPPEAVDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
1077,1125,DVSGVVCLSALPPEATDTLNLIASDGPFPYSQDGVVFQNRESVLPT...,7.0,NaN,48.4
12504,13447,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
12506,13449,MKALIVLGLVLLSVTVQGKVFERCELARTLKRLGMDGYRGISLANW...,2.7,NaN,64.9
13585,14640,MKMSRLCLSVALLVLLGTLAASTPGCDTSNQAKAQRPDFCLEPPYT...,7.0,NaN,39.0

After examining the update file, I found 2,409 rows with missing values in every column except seq_id. Following Kaggle's instructions, I deleted these rows from the training data. The other 25 rows correct entries where pH and tm were swapped in the original data, so I overwrote those rows with the corrected values from the update file. The cleaned dataset has 28,981 rows.

## Step 4: Missing values after updates

In [26]:
train_clean.isna().sum()

seq_id                0
protein_sequence      0
pH                  286
data_source         980
tm                    0
dtype: int64

In [27]:
(train_clean.isna().mean()*100).round(2)

seq_id              0.00
protein_sequence    0.00
pH                  0.99
data_source         3.38
tm                  0.00
dtype: float64

In [28]:
train_clean = train_clean.dropna(subset=["pH"])

In [29]:
train_clean.shape

(28695, 5)

In [30]:
28981-286

28695

In [31]:
# flaging the 3.38% of uncited rows 
train_clean["source_missing"] = train_clean["data_source"].isna()

In [32]:
# comparing group with sources vs those without 
train_clean.groupby("source_missing")["tm"].describe()

                  count       mean        std   min    25%    50%   75%    max
source_missing
False           27727.0  51.408039  12.031983  25.5  43.70  48.80  54.5  130.0
True              968.0  50.742975  13.282118  25.1  40.15  50.95  58.8   88.9

In [33]:
51.408039-50.742975

0.665064000000001

In [34]:
train_clean = train_clean.dropna(subset=["data_source"])

In [35]:
train_clean = train_clean.drop(columns="source_missing")

In [36]:
train_clean.shape

(27727, 5)

After applying the updates, 286 rows were missing pH. I dropped these rows because protein stability depends on pH, so the same protein can have a different melting temperature at a different pH. Without a recorded pH, a row's tm can't be compared fairly with the others. Since only 286 rows (about 1%) were affected, dropping them keeps the data consistent at little cost.

I also dropped the 968 remaining rows missing a citation in data_source. A missing citation doesn't make a measurement wrong, but it means the value can't be traced back to its source, which makes it less reliable. This concern is supported by the Kaggle update: 2,367 of the 2,409 rows Kaggle officially deleted were uncited. The tm values of the uncited rows were broadly similar to the cited ones, so this was a precaution rather than a response to clearly wrong values. The cleaned dataset now has 27,727 rows.

## Step 5: Out of Range values

In [37]:
#summary of pH values 
train_clean["pH"].describe()

count    27727.000000
mean         6.912643
std          0.715157
min          1.990000
25%          7.000000
50%          7.000000
75%          7.000000
max         11.000000
Name: pH, dtype: float64

In [38]:
#want to see if  there are any out of range pH values
train_clean[(train_clean["pH"]<0) | (train_clean["pH"]>14)]

Empty DataFrame
Columns: [seq_id, protein_sequence, pH, data_source, tm]
Index: []

In [39]:
#summary of temperture values
train_clean["tm"].describe()

count    27727.000000
mean        51.408039
std         12.031983
min         25.500000
25%         43.700000
50%         48.800000
75%         54.500000
max        130.000000
Name: tm, dtype: float64

In [41]:
##counting melting tempertures above 100 C 
(train_clean["tm"]>100).sum()

np.int64(7)

In [42]:
train_clean[train_clean["tm"]>100]

,seq_id,protein_sequence,pH,data_source,tm
13278,14318,MKKFLLVAVVGLAGITFANEQLAKQKGCMACHDLKAKKVGPAFADV...,7.00,10.1021/bi061164g,130.0
13279,14319,MKKFLLVAVVGLAGITFANEQLAKQKGCMACHDLKAKKVGPAFADV...,7.00,10.1021/bi061164g,116.0
13383,14424,MKKYTCTVCGYIYNPEDGDPDNGINPGTDFKDIPDDWVCPLCGVGK...,9.08,10.1016/j.bpc.2006.10.013,109.5
13384,14425,MKKYTCTVCGYIYNPEDGDPDNGVNPGTDFKDLPDDWVCPLCGVGK...,9.08,10.1016/j.bpc.2006.10.013,111.8
15241,16392,MLSRAVCGTSRQLAPVLGYLGSRQKHSLPDLPYDYGALEPHINAQI...,7.80,10.1021/bi9929958,103.0
26101,28463,MVEQDPFEIAVKQLERAAQYMDISEEALEFLKRPQRIVEVSIPVEM...,7.00,10.1073/pnas.95.21.12300,103.5
26102,28464,MVEQDPFEIAVKQLERAAQYMDISEEALEFLKRPQRIVEVSIPVEM...,7.00,10.1073/pnas.95.21.12300,108.5

To summarize the pH ranged from 1.99 to 11, so no values fell outside the valid range of 0 to 14 after the updates. Melting temperature ranged from 25.5 to 130°C, with 7 rows above 100°C. On closer inspection, all 7 had citations and normal pH values, and most came in pairs of nearly identical sequences (14318/14319, 14424/14425, 28463/28464), consistent with mutant comparisons from the same studies. Since proteins from hyperthermophiles can have melting temperatures above 100°C, I kept these rows.

## Step 6 : Duplicate sequences

In [43]:
train_clean["protein_sequence"].duplicated(keep=False).sum()

np.int64(1392)

In [44]:
dup_mask = train_clean.duplicated(subset=["protein_sequence", "pH"], keep=False)
dup_mask.sum()

np.int64(740)

In [51]:
train_clean[dup_mask].sort_values(["protein_sequence", "pH"])[["seq_id", "pH", "tm"]].head(10)

      seq_id   pH    tm
1715    1764  7.0  53.1
1716    1765  7.0  47.1
1889    1938  7.0  53.4
1890    1939  7.0  52.0
2190    2239  4.5  83.6
2191    2240  4.5  34.1
2192    2241  4.5  82.8
2193    2242  4.5  41.8
2194    2243  4.5  84.3
2195    2244  4.5  39.4

In [47]:
dup_groups = train_clean[dup_mask].groupby(["protein_sequence", "pH"])["tm"].agg(["count", "min", "max"])
dup_groups["tm_range"] = dup_groups["max"] - dup_groups["min"]
len(dup_groups)

341

In [48]:
dup_groups["tm_range"].describe()

count    341.000000
mean       5.187097
std        7.718420
min        0.000000
25%        0.700000
50%        1.700000
75%        7.100000
max       58.300000
Name: tm_range, dtype: float64

In [49]:
(dup_groups["tm_range"] == 0).sum()

np.int64(43)

740 duplicate rows form 341 groups (so about 2 copies per group, on average) and only 43 groups agree exactly.There is an explination for this we can see that half the groups disagree by 1.7°C or less. That's normal measurement noise between labs or repeat runs.The problem is that some disagree way too much for example seq_ids 2239 and 2240: same sequence, same pH 4.5, but tm 83.6 versus 34.1. That's a 49°C gap, and the max is 58.3°C. This is a problem both can't be right, and we can't tell which one is correct the best thing to do here is drop the pair.

In [52]:
(dup_groups["tm_range"]>5).sum()

np.int64(106)

Some proteins were measured more than once at the same pH. Leaving these copies in causes two problems. First, those proteins count twice in any summary or plot. Second, the data contradicts itself: for example, seq_ids 1764 and 1765 have the same sequence and pH but tm values of 53.1 and 47.1°C.

To fix this, I combined each set of copies into a single row and used the median tm as the best estimate. When copies disagreed by more than 5°C, I dropped them instead, because the measurements conflict and there is no way to tell which is correct. I chose 5°C because it is above typical measurement noise but below the clearly conflicting cases, such as seq_ids 2239 and 2240, which differ by 49°C.

In [53]:
# Combine rows with the same sequence and pH into one row.
# Rows that appear only once pass through unchanged.
# tm_min and tm_max are kept temporarily to measure disagreement.

train_dedup = train_clean.groupby(["protein_sequence", "pH"], as_index=False).agg(
    seq_id=("seq_id", "first"),
    data_source=("data_source", "first"),
    tm=("tm", "median"),
    tm_min=("tm", "min"),
    tm_max=("tm", "max"),
)
train_dedup.shape

(27328, 7)

In [54]:
# Drop groups whose copies disagree by more than 5 degrees C, then remove helper columns.
train_dedup = train_dedup[(train_dedup["tm_max"] - train_dedup["tm_min"]) <= 5]
train_dedup = train_dedup.drop(columns=["tm_min", "tm_max"])
train_dedup.shape

(27222, 5)

In summary of the 740 duplicate rows, 43 groups agreed exactly and 106 disagreed by more than 5°C and were dropped. The remaining groups were combined using their median tm. The final cleaned dataset has 27,222 rows.